/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.patterns.java;

import design.patterns.java.chapter02.CurrentConditionsDisplay;
import design.patterns.java.chapter02.WeatherData;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        WeatherData wd = new WeatherData();
        CurrentConditionsDisplay cd = new CurrentConditionsDisplay(wd);
        wd.setMeasurements(80, 65, 30.4f);
        wd.setMeasurements(82, 70, 30.2f);
        wd.setMeasurements(78, 90, 29.2f);
    }
}
